import './globals.css';
import type { Metadata } from 'next';
import { Navbar } from 'components/Navbar';
import { ReduxProvider } from 'components/ReduxProvider';
import { DivContainer } from './components/DivContainer';
import { SocketProvider } from './hooks/socketContext';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <SocketProvider>
        <Navbar/>
        <ReduxProvider>
          <DivContainer className={"body-container"}>
            {children}
          </DivContainer>
        </ReduxProvider>
      </SocketProvider>
      </body>
    </html>
  )
}
