import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Navbar } from 'components/Navbar'
import { ReduxProvider } from 'components/ReduxProvider'
import { DivContainer } from './components/DivContainer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <ReduxProvider>
          <DivContainer className={"body-container"}>
            {children}
          </DivContainer>
        </ReduxProvider>
      </body>
    </html>
  )
}
